### ISSUE TITLE
autoCreateTable does not use SinkRecord.keySchema to build org.apache.iceberg.Schema and meet exception when parse deleting opertion record

### ISSUE THREAD

**Issue by xq2005** [tabular-io/iceberg-kafka-connect#128]
In function [autoCreateTable](https://github.com/tabular-io/iceberg-kafka-connect/blob/e7449efefb27877a51bf4508e6858a1d691e55c8/kafka-connect/src/main/java/io/tabular/iceberg/connect/data/IcebergWriterFactory.java#L74),  org.apache.iceberg.Schema does not supply the identifierFieldIds. 

When parsing delete operation record, meet the following exception:

Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:195)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:631)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.DataException: An error occurred converting record, topic: linux.pg_kafka.sourcedb.product, partition, 0, offset: 240
        at io.tabular.iceberg.connect.data.IcebergWriter.write(IcebergWriter.java:73)
        at io.tabular.iceberg.connect.channel.Worker.routeRecordDynamically(Worker.java:231)
        at io.tabular.iceberg.connect.channel.Worker.save(Worker.java:186)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at io.tabular.iceberg.connect.channel.Worker.save(Worker.java:174)
        at io.tabular.iceberg.connect.IcebergSinkTask.put(IcebergSinkTask.java:145)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:601)
        ... 10 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at io.tabular.iceberg.connect.data.RecordProjection.get(RecordProjection.java:149)
        at io.tabular.iceberg.connect.data.RecordProjection.get(RecordProjection.java:188)
        at org.apache.iceberg.data.parquet.GenericParquetWriter$RecordWriter.get(GenericParquetWriter.java:48)
        at org.apache.iceberg.data.parquet.GenericParquetWriter$RecordWriter.get(GenericParquetWriter.java:41)
        at org.apache.iceberg.parquet.ParquetValueWriters$StructWriter.write(ParquetValueWriters.java:588)
        at org.apache.iceberg.parquet.ParquetWriter.add(ParquetWriter.java:139)
        at org.apache.iceberg.deletes.EqualityDeleteWriter.write(EqualityDeleteWriter.java:67)
        at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.write(BaseTaskWriter.java:388)
        at org.apache.iceberg.io.BaseTaskWriter$RollingEqDeleteWriter.write(BaseTaskWriter.java:371)
        at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.write(BaseTaskWriter.java:277)
        at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.deleteKey(BaseTaskWriter.java:186)
        at io.tabular.iceberg.connect.data.BaseDeltaTaskWriter.write(BaseDeltaTaskWriter.java:77)
        at io.tabular.iceberg.connect.data.UnpartitionedDeltaWriter.write(UnpartitionedDeltaWriter.java:30)
        at io.tabular.iceberg.connect.data.BaseDeltaTaskWriter.write(BaseDeltaTaskWriter.java:36)
        at io.tabular.iceberg.connect.data.IcebergWriter.write(IcebergWriter.java:68)
        ... 16 more

**Comment by bryanck** [comment]
Can you post the record value causing this?

**Comment by xq2005** [comment]
The fix is very directly, 
if `key_schema `is contained in SinkRecord, scaning the valueSchema's structType to find the mapping id and build the identifierFieldIds.
if `iceberg.table.<table name>.id-columns` is defined in the configuration file, scaning the valueSchema's structType to find the mapping id and build the identifierFieldIds.
else use null.


```java
    Set<Integer> equalityFieldIds = ImmutableSet.of();
    if (sample.keySchema() != null) {
      equalityFieldIds =
          sample.keySchema().fields().stream()
              .map(f -> structType.field(f.name()).fieldId())
              .collect(toSet());
    } 
    List<String> idCols = config.tableConfig(tableName).idColumns();
    if (!idCols.isEmpty()) {
      equalityFieldIds =
        idCols.stream()
            .map(colName -> structType.field(colName).fieldId())
            .collect(toSet());
    }


    org.apache.iceberg.Schema schema =
        new org.apache.iceberg.Schema(structType.fields(), equalityFieldIds);
``` 

[ iceberg.table.\<table name\>.id-columns handle code ](https://github.com/tabular-io/iceberg-kafka-connect/blob/e7449efefb27877a51bf4508e6858a1d691e55c8/kafka-connect/src/main/java/io/tabular/iceberg/connect/data/Utilities.java#L170) in createTableWriter can be deleted.

**Comment by bryanck** [comment]
The sink relies on the record value and makes no assumptions about the structure of the record key. You can use an SMT to copy the key to the value if you want.

**Comment by xq2005** [comment]
> The sink relies on the record value and makes no assumptions about the structure of the record key. You can use an SMT to copy the key to the value if you want.

yes, SMT is a good idea, ant I need write a complex transformer.

**Comment by bryanck** [comment]
The Debezium SMT in this repo does this, copies the key to a field in the value. It isn't very complex.

**Comment by xq2005** [comment]
OK. I can have a try.
